import type { MutableRefObject } from "react";
import type { GameState, LoseReason, UIScreen } from "../../game/model/types";

export type UseGameUiActionsParams = {
  stateRef: MutableRefObject<GameState>;
  gameNowRef: MutableRefObject<number>;
  keysRef: MutableRefObject<Set<string>>;
  screenRef: MutableRefObject<UIScreen>;
  touchEnabledRef: MutableRefObject<boolean>;
  mapOpenRef: MutableRefObject<boolean>;
  confirmRestartRef: MutableRefObject<boolean>;
  pausedRef: MutableRefObject<boolean>;
  equipmentOpenRef: MutableRefObject<boolean>;
  controlsReturnToGameRef: MutableRefObject<boolean>;
  bestiaryReturnToGameRef: MutableRefObject<boolean>;
  mapReturnToPauseRef: MutableRefObject<boolean>;
  resetTouchInput: () => void;
  setScreen: (value: UIScreen) => void;
  setStatus: (value: "playing" | "win" | "lose") => void;
  setItemsLeft: (value: number) => void;
  setCoinsCollected: (value: number) => void;
  setSpikesLeft: (value: number) => void;
  setBombsLeft: (value: number) => void;
  setLoseReason: (value: LoseReason) => void;
  setConfirmRestartOpen: (value: boolean) => void;
  setPaused: (value: boolean) => void;
  setEquipmentOpen: (value: boolean) => void;
  setControlsReturnToGame: (value: boolean) => void;
  setBestiaryReturnToGame: (value: boolean) => void;
  setMapOpen: (value: boolean) => void;
};
